env:
  - name: DS_GLOBAL_OCA_REPOSITORY_BUNDLES_URL
    value: "https://oca-repository.marketplace.nextgen.hiro-develop.nl/api/v2/oca-bundles"
  - name: LOG_LEVEL
    value: "DEBUG"

ingress:
  host: nextgen.hiro-develop.nl

nodeSelector:
  role: marketplace

namespace: marketplace
