env:
  - name : LOG_LEVEL
    value: "INFO"

  - name: ORDER_TTL_SECONDS
    value: "7200" # 120 minutes
  - name: ORDER_KEY_PREFIX
    value: "order:"  # Prefix for order keys in storage
  - name: ORDER_TTL_ENABLED
    value: "true"
  - name: MAX_PAYLOAD_SIZE_BYTES
    value: "10485760" # 10 MB
  - name:  DS_CONNECTOR_BASE_URL
    value: "https://ds-connector.{region}.nextgen.hiro-develop.nl/distribution-content"


  - name: DATABASE__PROTOCOL
    value: "redis"
  - name: DATABASE__HOST
    value: "redis-repository"
  - name: DATABASE__PORT
    value: "6379"
  - name: DATABASE__DB_NUMBER
    value: "0"
  - name: DATABASE__USERNAME
    value: ""
  - name: DATABASE__PASSWORD
    valueFrom:
      secretKeyRef:
        name: redis-credentials
        key: password

  - name: TEST_DATABASE__PROTOCOL
    value: "redis"
  - name: TEST_DATABASE__HOST
    value: "redis-repository"
  - name: TEST_DATABASE__PORT
    value: "6379"
  - name: TEST_DATABASE__DB_NUMBER
    value: "15"
  - name: TEST_DATABASE__USERNAME
    value: ""
  - name: TEST_DATABASE__PASSWORD
    valueFrom:
      secretKeyRef:
        name: redis-credentials
        key: password

ingress:
  enabled: true
  host: nextgen.hiro-develop.nl
  
nodeSelector:
  role: marketplace

namespace: marketplace

metrics:
  enabled: true