nodeSelector:
  role: uva

namespace: uva

ingress:
  host: nextgen.hiro-develop.nl

backend:
  catalogName: "uva_catalog"
  searchServiceURL: https://ds-gateway.uva.nextgen.hiro-develop.nl/search
  catalogServiceURL: https://ds-gateway.uva.nextgen.hiro-develop.nl/catalog
  connectorServiceURL: https://ds-connector.hus.nextgen.hiro-develop.nl/dataproducts
  trainingBuilderServiceURL: https://dashboard.cog.hiro-develop.nl/apidev
  cogURL: https://dashboard.cog.hiro-develop.nl/uidev/
  apiCogURL: https://dashboard.cog.hiro-develop.nl/apidev
