nodeSelector:
  role: hus

namespace: hus

ingress:
  host: nextgen.hiro-develop.nl

backend:
  catalogName: "hus_catalog"
  searchServiceURL: https://ds-gateway.hus.nextgen.hiro-develop.nl/search
  catalogServiceURL: https://ds-gateway.hus.nextgen.hiro-develop.nl/catalog
  connectorServiceURL: https://ds-connector.hus.nextgen.hiro-develop.nl/dataproducts
  trainingBuilderServiceURL: https://dashboard.cog.hiro-develop.nl/apidev
  cogUrl: https://dashboard.cog.hiro-develop.nl/uidev/
  apiCogUrl: https://dashboard.cog.hiro-develop.nl/apidev
